### ISSUE TITLE
the sidebar is unnecessarily large 

### ISSUE THREAD

**Issue by ernieIzde8ski** [qAndroidGit/rounded-dark-theme#1]
With theme:
![image](https://user-images.githubusercontent.com/44341687/90274445-93ef0b00-de2e-11ea-8393-105795e63973.png)
versus without:
![image](https://user-images.githubusercontent.com/44341687/90274900-648cce00-de2f-11ea-9f69-62ca122bee67.png)
The length of the sidebar currently tends to be at least double the size of most channel names, like this ![image](https://user-images.githubusercontent.com/44341687/90275019-9f8f0180-de2f-11ea-999a-e35246d503e7.png)

**Comment by Bolimha1234** [comment]
In theme.css you can less that amount changing the value of sidebar-2K8pFh
```css
.sidebar-2K8pFh {
    width: 200px;
}

**Comment by ernieIzde8ski** [comment]
спасибо 👍
